services:
  - type: web
    name: kekego
    runtime: python
    rootDir: .
    buildCommand: >-
      pip install -r KekeGo/requirements.txt &&
      npm install --prefix student-app &&
      npm run build --prefix student-app &&
      python manage.py collectstatic --noinput
    startCommand: gunicorn KekeGo.wsgi:application
