# Generated by Django 5.2.17 on 2026-09-14 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=20)),
                ('plate_number', models.CharField(max_length=20)),
                ('rating', models.DecimalField(decimal_places=1, default=4.8, max_digits=3)),
            ],
        ),
    ]
