# Generated by Django 5.2.17 on 2026-09-14 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('pickup', models.CharField(max_length=120)),
                ('destination', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('FULL', 'Full'), ('SEARCHING_DRIVER', 'Searching driver'), ('DRIVER_ASSIGNED', 'Driver assigned'), ('DRIVER_ACCEPTED', 'Driver accepted'), ('IN_TRIP', 'In trip'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='WAITING', max_length=30)),
                ('total_seats', models.PositiveSmallIntegerField(default=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='groups.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('group', 'student'), name='unique_group_member')],
            },
        ),
    ]
