# Generated by Django 5.2.17 on 2026-09-14 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('pickup', models.CharField(max_length=120)),
                ('destination', models.CharField(max_length=120)),
                ('passengers', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('DRIVER_ASSIGNED', 'Driver assigned'), ('DRIVER_ACCEPTED', 'Driver accepted'), ('IN_TRIP', 'In trip'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRIVER_ASSIGNED', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='drivers.driver')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trip', to='groups.group')),
            ],
        ),
    ]
